### ISSUE TITLE
Feature roadmap towards 1.0

### ISSUE THREAD

**Issue by Bubblbu** [Bubblbu/zotnote#7]
This is the feature roadmap for ZotNote.

At this stage of the project, this roadmap will change quite a bit. However, each feature release will have a project page associated.

All previous changes are logged in the [changelog](https://github.com/Bubblbu/zotnote/blob/master/CHANGELOG.md).

### 0.4 | Testing

- [ ] Testing
   - [ ] Implement tests with `pytest`
   - [ ] Use Coveralls
   - [ ] Setup Travis CI
- [ ] Documentation
   - [ ] Choose framework
   - [ ] Write super basic documentation
- [x] Manage multiple results for citekey search
   - [x] Find out if we can retrieve formatted citations through BBT
- [ ] Fundamentally rethink and rewrite the model of Zotero items <-> Notes including the role of citekeys and Zotero IDs
   - [ ] Add Item class for objects retrieved from BBT
   - [ ] Rework Note class

### 0.5 | Collections & Tags

- [ ] Development of *collections*
   - Manage multiple notes as one collection. e.g., `zotnote create -c PhD` creates a new PhD collection. `zotnote add -c PhD [citekey]` will create a new reading note for [citekey] in that collection
- [ ] Development of the *tags*
    - Add possibility to tag reading notes. Import might be provided from Zotero, but also provided through a command line option (e.g., `zotnote add -t important [citekey]`

### 0.6 | Exports

- [ ] Development of *reading note export*
    - Export individual papers to different formats using [pandoc](https://pandoc.org/):
        - .pdf (*priority*)
        - .docx

### 0.7 | Reports

- [ ] Development of *reports*
    - Create reports on collections or sets of reading notes (selected by tags)
    - Use Jupyter notebooks to export report as PDF or HTML
    - Basic analytics of progress, wordcounts, etc.
 

### 0.8 | Advanced exports and collections

- [ ] Process collections/set of notes into note summaries such as annotated bibliographies
